import { EmployeeShiftSwapMobile } from './employeeWeb';
import {
  EmployeeContractDetailWeb,
  EmployeeLateReportWeb,
  EmployeeMemoCreateWeb,
  EmployeeNotificationMobile,
  EmployeeNotificationWeb,
  LoginWeb,
  OwnerLaborMobile,
  OwnerNotificationMobile,
  OwnerNotificationWeb,
  OwnerPaymentMobile,
  OwnerProfileEditMobile,
  OwnerProfileWeb,
  OwnerScheduleEditWeb,
  OwnerStaffEditWeb,
  OwnerStatsMobile,
  OwnerTaxationMobile,
  OwnerTodoWeb,
  PasswordResetWeb,
  RoleSelectWeb,
  StaffInviteWeb,
  StaffJoinWeb,
  StoreRegisterStep2Web,
  StoreRegisterWeb,
  ThemePreviewDusk,
  ThemePreviewMinimal,
} from './latestAdditions';
import type { AttendanceScreen } from './screenTypes';

export const latestAdditionScreens: AttendanceScreen[] = [
  { id: 'latest-theme-dusk', label: 'A · Dusk', group: '디자인 테마', width: 260, height: 480, viewport: 'custom', Component: ThemePreviewDusk },
  { id: 'latest-theme-minimal', label: 'B · Minimal', group: '디자인 테마', width: 260, height: 480, viewport: 'custom', Component: ThemePreviewMinimal },
  { id: 'latest-login-web', label: '09 · 로그인 (웹)', group: '온보딩', width: 1280, height: 800, viewport: 'web', Component: LoginWeb },
  { id: 'latest-password-reset-web', label: '10 · 비밀번호 찾기 (웹)', group: '온보딩', width: 1280, height: 800, viewport: 'web', Component: PasswordResetWeb },
  { id: 'latest-role-select-web', label: '03-B · 역할 선택 (웹)', group: '온보딩', width: 1280, height: 800, viewport: 'web', Component: RoleSelectWeb },
  { id: 'latest-store-register-web', label: '04-C · 매장 등록 1/3 (웹)', group: '온보딩', width: 1280, height: 800, viewport: 'web', Component: StoreRegisterWeb },
  { id: 'latest-store-register-step2-web', label: '04-D · 매장 등록 2/3 (웹)', group: '온보딩', width: 1280, height: 800, viewport: 'web', Component: StoreRegisterStep2Web },
  { id: 'latest-staff-invite-web', label: '05-B · 직원 초대 (웹)', group: '온보딩', width: 1280, height: 800, viewport: 'web', Component: StaffInviteWeb },
  { id: 'latest-staff-join-web', label: '07-B · 직원 코드 입력 (웹)', group: '온보딩', width: 1280, height: 800, viewport: 'web', Component: StaffJoinWeb },
  { id: 'latest-employee-shift-swap-mobile', label: 'M3b · 근무 교환 신청 (직원 모바일)', group: '직원 일정관리', width: 390, height: 844, viewport: 'mobile', Component: EmployeeShiftSwapMobile },
  { id: 'latest-employee-notification-mobile', label: 'M10 · 알림 (모바일)', group: '직원 알림', width: 390, height: 844, viewport: 'mobile', Component: EmployeeNotificationMobile },
  { id: 'latest-owner-profile-edit-mobile', label: 'OM8 · 프로필 수정 (사장 모바일)', group: '경영주 프로필', width: 390, height: 844, viewport: 'mobile', Component: OwnerProfileEditMobile },
  { id: 'latest-owner-notification-mobile', label: 'OM9 · 알림 (사장 모바일)', group: '경영주 알림', width: 390, height: 844, viewport: 'mobile', Component: OwnerNotificationMobile },
  { id: 'latest-owner-stats-mobile', label: 'OM11 · 통계 리포트 (사장 모바일)', group: '경영주 통계리포트', width: 390, height: 844, viewport: 'mobile', Component: OwnerStatsMobile },
  { id: 'latest-owner-taxation-mobile', label: 'OM12 · 세무사 연결 (사장 모바일)', group: '경영주 세무사연결', width: 390, height: 844, viewport: 'mobile', Component: OwnerTaxationMobile },
  { id: 'latest-owner-labor-mobile', label: 'OM13 · 근로계약서 (사장 모바일)', group: '경영주 계약서', width: 390, height: 844, viewport: 'mobile', Component: OwnerLaborMobile },
  { id: 'latest-owner-payment-mobile', label: 'OM14 · 결제·구독 (사장 모바일)', group: '경영주 결제구독', width: 390, height: 844, viewport: 'mobile', Component: OwnerPaymentMobile },
  { id: 'latest-employee-notification-web', label: 'EW9 · 알림 (직원 웹)', group: '직원 알림', width: 1280, height: 800, viewport: 'web', Component: EmployeeNotificationWeb },
  { id: 'latest-employee-late-report-web', label: 'EW10 · 지각·결근 보고 (직원 웹)', group: '직원 근태보고', width: 1280, height: 800, viewport: 'web', Component: EmployeeLateReportWeb },
  { id: 'latest-employee-memo-create-web', label: 'EW11 · 메모·게시글 작성 (직원 웹)', group: '직원 메모', width: 1280, height: 800, viewport: 'web', Component: EmployeeMemoCreateWeb },
  { id: 'latest-employee-contract-detail-web', label: 'EW12 · 계약서 상세 (직원 웹)', group: '직원 계약서', width: 1280, height: 800, viewport: 'web', Component: EmployeeContractDetailWeb },
  { id: 'latest-owner-schedule-edit-web', label: 'F3b · 근무 수정 (웹 모달)', group: '경영주 일정관리', width: 1280, height: 800, viewport: 'web', Component: OwnerScheduleEditWeb },
  { id: 'latest-owner-staff-edit-web', label: 'F5b · 직원 정보 수정 (웹 모달)', group: '경영주 직원관리', width: 1280, height: 800, viewport: 'web', Component: OwnerStaffEditWeb },
  { id: 'latest-owner-notification-web', label: 'D13 · 알림 (사장 웹)', group: '경영주 알림', width: 1280, height: 800, viewport: 'web', Component: OwnerNotificationWeb },
  { id: 'latest-owner-profile-web', label: 'D12 · 내 계정·프로필 (사장 웹)', group: '경영주 프로필', width: 1280, height: 800, viewport: 'web', Component: OwnerProfileWeb },
  { id: 'latest-owner-todo-web', label: 'D14 · 할 일 관리 (사장 웹)', group: '경영주 할 일', width: 1280, height: 800, viewport: 'web', Component: OwnerTodoWeb },
];
