import {
  OwnerAttendanceWeb,
  OwnerDashboardWeb,
  OwnerLaborCreateWeb,
  OwnerLaborPreviewWeb,
  OwnerLaborWeb,
  OwnerLeaveWeb,
  OwnerMemoCreateWeb,
  OwnerMemoWeb,
  OwnerPaymentCheckoutWeb,
  OwnerPaymentWeb,
  OwnerPayrollWeb,
  OwnerPushMessageCreateWeb,
  OwnerScheduleCreateWeb,
  OwnerScheduleWeb,
  OwnerStaffAddWeb,
  OwnerStaffWeb,
  OwnerStatsWeb,
  OwnerTaxationWeb,
} from './ownerWeb';
import type { AttendanceScreen } from './screenTypes';

export const ownerWebScreens: AttendanceScreen[] = [
  { id: 'owner-dashboard-web', label: '01 · 대시보드', group: '경영주 웹', width: 1280, height: 800, viewport: 'web', Component: OwnerDashboardWeb },
  { id: 'owner-schedule-web', label: '02 · 스케줄 편성', group: '경영주 웹', width: 1280, height: 800, viewport: 'web', Component: OwnerScheduleWeb },
  { id: 'owner-schedule-create-web', label: 'F3 · 일정 추가 (웹 모달)', group: '경영주 웹', width: 1280, height: 800, viewport: 'web', Component: OwnerScheduleCreateWeb },
  { id: 'owner-payroll-web', label: '03 · 급여 관리', group: '경영주 웹', width: 1280, height: 800, viewport: 'web', Component: OwnerPayrollWeb },
  { id: 'owner-staff-web', label: '04 · 직원 관리', group: '경영주 웹', width: 1280, height: 800, viewport: 'web', Component: OwnerStaffWeb },
  { id: 'owner-staff-add-web', label: 'F4 · 직원 추가 (웹 모달)', group: '경영주 웹', width: 1280, height: 800, viewport: 'web', Component: OwnerStaffAddWeb },
  { id: 'owner-attendance-web', label: '05 · 근태 현황', group: '경영주 웹', width: 1280, height: 800, viewport: 'web', Component: OwnerAttendanceWeb },
  { id: 'owner-memo-web', label: '06 · 메모·인수인계', group: '경영주 웹', width: 1280, height: 800, viewport: 'web', Component: OwnerMemoWeb },
  { id: 'owner-memo-create-web', label: 'F5 · 메모·공지 작성 (웹 모달)', group: '경영주 웹', width: 1280, height: 800, viewport: 'web', Component: OwnerMemoCreateWeb },
  { id: 'owner-push-message-create-web', label: 'F6 · 직원 알림 보내기 (웹 모달)', group: '경영주 웹', width: 1280, height: 800, viewport: 'web', Component: OwnerPushMessageCreateWeb },
  { id: 'owner-leave-web', label: '07 · 휴가·연차 관리', group: '경영주 웹', width: 1280, height: 800, viewport: 'web', Component: OwnerLeaveWeb },
  { id: 'owner-stats-web', label: '08 · 통계 리포트', group: '경영주 웹', width: 1280, height: 800, viewport: 'web', Component: OwnerStatsWeb },
  { id: 'owner-taxation-web', label: 'D9 · 세무사 연결', group: '경영주 웹', width: 1280, height: 800, viewport: 'web', Component: OwnerTaxationWeb },
  { id: 'owner-labor-web', label: 'D10 · 근로계약서', group: '경영주 웹', width: 1280, height: 800, viewport: 'web', Component: OwnerLaborWeb },
  { id: 'owner-labor-create-web', label: 'D10b · 근로계약서 작성 폼', group: '경영주 웹', width: 1280, height: 800, viewport: 'web', Component: OwnerLaborCreateWeb },
  { id: 'owner-labor-preview-web', label: 'D10c · 계약서 미리보기·다운로드·업로드', group: '경영주 웹', width: 1280, height: 800, viewport: 'web', Component: OwnerLaborPreviewWeb },
  { id: 'owner-payment-web', label: 'D11 · 결제·구독 관리', group: '경영주 웹', width: 1280, height: 800, viewport: 'web', Component: OwnerPaymentWeb },
  { id: 'owner-payment-checkout-web', label: 'D11b · 결제 위젯 (토스페이먼츠)', group: '경영주 웹', width: 1280, height: 800, viewport: 'web', Component: OwnerPaymentCheckoutWeb },
];
